package org.hl7.fhir.instance.model;

public enum ResourceType {
    Provenance,
    Device,
    Order,
    Organization,
    Prescription,
    Group,
    ValueSet,
    Coverage,
    Test,
    MedicationAdministration,
    SecurityEvent,
    IssueReport,
    List,
    LabReport,
    Conformance,
    XdsEntry,
    Document,
    Message,
    Profile,
    Observation,
    Immunization,
    Problem,
    OrderResponse,
    Patient,
    XdsEntry2,
    Provider,
    XdsFolder,
    Medication,
    Specimen,
    Food,
    Location,
    Procedure,
    Admission,
    Substance,
    AnatomicalLocation,
    InterestOfCare;

}
