package org.hl7.fhir.instance.model;

public enum ResourceType {
    CarePlan,
    Provenance,
    Device,
    Order,
    Organization,
    Prescription,
    Group,
    DiagnosticReport,
    ValueSet,
    Coverage,
    Test,
    MedicationAdministration,
    SecurityEvent,
    IssueReport,
    List,
    Picture,
    Conformance,
    XdsEntry,
    Document,
    Message,
    Profile,
    Observation,
    Immunization,
    Problem,
    OrderResponse,
    Patient,
    ImagingStudy,
    XdsEntry2,
    Provider,
    XdsFolder,
    Medication,
    Specimen,
    Food,
    Encounter,
    Location,
    Procedure,
    Request,
    Admission,
    Substance,
    AnatomicalLocation,
    InterestOfCare,
    Binary;

}
